# Generated by Django 3.1.7 on 2021-04-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hash_calculators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hash_function',
            name='output_size_in_bits',
            field=models.IntegerField(),
        ),
    ]
