# Generated by Django 3.1.7 on 2021-04-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hash_calculators', '0002_auto_20210404_1934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hash_Function',
            new_name='HashFunction',
        ),
    ]
